/*
 * fuzzy_type1.h -- Fuzzy inference evaluator (AUTO-GENERATED).
 *
 * Generated by fis2c.py from FIS "fuzzy_type1". DO NOT EDIT BY HAND.
 * To change rules / membership functions, edit the .fis and re-run:
 *     python3 fis2c.py fuzzy_type1.fis
 *
 * System    : mamdani fuzzy inference
 * Inputs    : 2   (pass them to the evaluator in the order below)
 * Outputs   : 1
 * Methods   : AND=min  implication=min  aggregation=max  defuzz=centroid
 *
 * Inputs (evaluator argument order):
 *   [0] 'e'        range [-1, 1]
 *   [1] 'ed'       range [-1, 1]
 *
 * Outputs:
 *   [0] 'output1'  range [-1, 1]
 *
 * Notes:
 *   - Inputs are NOT clamped internally; the membership functions are
 *     defined over the whole real line, so out-of-range values still
 *     evaluate. Scale your physical signals into the ranges above
 *     (e.g. normalized error in [-1, 1]) before calling.
 *   - The evaluator is reentrant (no mutable static state) and safe to
 *     call from multiple threads / a real-time control loop.
 *   - Cost per call is O(N_rules * N_output_samples); trivial for a
 *     kHz-class control loop.
 *
 * Usage (C):
 *     #include "fuzzy_type1.h"
 *     float u = fuzzy_type1_eval(e, ed);   // single-output shortcut
 *     // -- or, array form --
 *     float in[2] = {e, ed};
 *     float out[1];
 *     fuzzy_type1_eval_core(in, out);
 *
 * Usage (C++): the declarations below are wrapped in extern "C",
 *     so just #include this header directly from a .cpp file.
 *
 * Build:
 *     gcc  app.c fuzzy_type1.c -lm
 *     g++  app.cpp fuzzy_type1.c -lm
 */

#ifndef FUZZY_TYPE1_H
#define FUZZY_TYPE1_H

#ifdef __cplusplus
extern "C" {
#endif

/*
 * fuzzy_type1_eval_core -- evaluate the FIS from flat arrays.
 *
 *   in[2] : input values, in the order listed at the top of this file
 *           (e, ed).
 *   out[1]: resulting output value(s).
 *
 * Use this form when the number of inputs/outputs is not known at
 * compile time, or from a generic controller loop. Reentrant.
 */
void fuzzy_type1_eval_core(const float * in, float * out);

/*
 * fuzzy_type1_eval -- convenience wrapper for the single-output case.
 *
 *   e            : input 'e'
 *   ed           : input 'ed'
 *   returns    : out[0] ('output1').
 *
 * Equivalent to packing the arguments into in[2] and returning out[0].
 */
float fuzzy_type1_eval(float e, float ed);

#ifdef __cplusplus
}
#endif

#endif /* FUZZY_TYPE1_H */
