/* Auto-generated by fis2c.py from FIS "fuzzy_type11". Do not edit by hand. */
#include "fuzzy_type11.h"
#include <math.h>

#define FUZZY_NI 2
#define FUZZY_NO 1
#define FUZZY_NR 25
#define FUZZY_MAXMI 5
#define FUZZY_MAXMO 5
#define FUZZY_N 201

typedef enum {
    MF_GAUSSMF, MF_ZMF, MF_SMF, MF_TRIMF, MF_TRAPMF, MF_GBELL, MF_PIMF, MF_SIGMF, MF_CONST
} MFType;

typedef struct { MFType type; float p[4]; } MFDef;

static float mu_gauss(float s, float c, float x) {
    if (s == 0.0f) return (x == c) ? 1.0f : 0.0f;
    float d = (x - c) / s;
    return expf(-0.5f * d * d);
}
static float mu_zmf(float a, float b, float x) {
    if (a == b) return (x <= a) ? 1.0f : 0.0f;
    if (x <= a) return 1.0f;
    if (x >= b) return 0.0f;
    float m = 0.5f * (a + b), t;
    if (x <= m) { t = (x - a) / (b - a); return 1.0f - 2.0f * t * t; }
    t = (b - x) / (b - a);
    return 2.0f * t * t;
}
static float mu_smf(float a, float b, float x) {
    if (a == b) return (x >= a) ? 1.0f : 0.0f;
    if (x <= a) return 0.0f;
    if (x >= b) return 1.0f;
    float m = 0.5f * (a + b), t;
    if (x <= m) { t = (x - a) / (b - a); return 2.0f * t * t; }
    t = (b - x) / (b - a);
    return 1.0f - 2.0f * t * t;
}
static float mf_eval(MFType type, const float p[4], float x) {
    switch (type) {
    case MF_GAUSSMF: return mu_gauss(p[0], p[1], x);
    case MF_ZMF:     return mu_zmf(p[0], p[1], x);
    case MF_SMF:     return mu_smf(p[0], p[1], x);
    case MF_TRIMF: {
        float a = p[0], b = p[1], c = p[2];
        if (x <= a || x >= c) return 0.0f;
        if (x <= b) { if (b == a) return 1.0f; return (x - a) / (b - a); }
        if (c == b) return 1.0f;
        return (c - x) / (c - b);
    }
    case MF_TRAPMF: {
        float a = p[0], b = p[1], c = p[2], d = p[3];
        if (x <= a || x >= d) return 0.0f;
        if (x >= b && x <= c) return 1.0f;
        if (x < b) { if (b == a) return 1.0f; return (x - a) / (b - a); }
        if (d == c) return 1.0f;
        return (d - x) / (d - c);
    }
    case MF_GBELL: {
        float a = p[0], b = p[1], c = p[2];
        if (a == 0.0f) return (x == c) ? 1.0f : 0.0f;
        float t = fabsf((x - c) / a);
        return 1.0f / (1.0f + powf(t, 2.0f * b));
    }
    case MF_PIMF: {
        float s = mu_smf(p[0], p[1], x), z = mu_zmf(p[2], p[3], x);
        return (s < z) ? s : z;
    }
    case MF_SIGMF:
        return 1.0f / (1.0f + expf(-p[0] * (x - p[1])));
    case MF_CONST:
        return p[0];
    }
    return 0.0f;
}

static float t_norm(float a, float b) { return (a < b) ? a : b; } /* AND=min */
static float s_norm(float a, float b) { return (a > b) ? a : b; } /* AGG=max */
static float imp(float w, float mu) { return (w < mu) ? w : mu; } /* IMP=min */

static const int in_nmf[FUZZY_NI] = {5, 5};
static const MFDef in_mf[FUZZY_NI][FUZZY_MAXMI] = {
  {{MF_TRAPMF, {-1.0f, -1.0f, -0.66f, -0.33f}}, {MF_TRIMF, {-0.75f, -0.33f, 0.1f, 0.0f}}, {MF_TRIMF, {-0.45f, 0.0f, 0.45f, 0.0f}}, {MF_TRIMF, {-0.1f, 0.33f, 0.75f, 0.0f}}, {MF_TRAPMF, {0.33f, 0.66f, 1.0f, 1.0f}}},
  {{MF_TRAPMF, {-1.0f, -1.0f, -0.66f, -0.33f}}, {MF_TRIMF, {-0.75f, -0.33f, 0.1f, 0.0f}}, {MF_TRIMF, {-0.45f, 0.0f, 0.45f, 0.0f}}, {MF_TRIMF, {-0.1f, 0.33f, 0.75f, 0.0f}}, {MF_TRAPMF, {0.33f, 0.66f, 1.0f, 1.0f}}}
};

static const int out_nmf[FUZZY_NO] = {5};
static const MFDef out_mf[FUZZY_NO][FUZZY_MAXMO] = {
  {{MF_TRAPMF, {-1.0f, -1.0f, -0.66f, -0.33f}}, {MF_TRIMF, {-0.75f, -0.33f, 0.1f, 0.0f}}, {MF_TRIMF, {-0.45f, 0.0f, 0.45f, 0.0f}}, {MF_TRIMF, {-0.1f, 0.33f, 0.75f, 0.0f}}, {MF_TRAPMF, {0.33f, 0.66f, 1.0f, 1.0f}}}
};

static const float out_lo[FUZZY_NO] = {-1.0f};
static const float out_hi[FUZZY_NO] = {1.0f};

typedef struct { int in[FUZZY_NI]; int out[FUZZY_NO]; float weight; int conn; } FuzzyRule;
static const FuzzyRule rules[FUZZY_NR] = {
  { { 1, 1 }, { 1 }, 1.0f, 1 },
  { { 2, 1 }, { 1 }, 1.0f, 1 },
  { { 3, 1 }, { 1 }, 1.0f, 1 },
  { { 4, 1 }, { 2 }, 1.0f, 1 },
  { { 5, 1 }, { 3 }, 1.0f, 1 },
  { { 1, 2 }, { 1 }, 1.0f, 1 },
  { { 2, 2 }, { 1 }, 1.0f, 1 },
  { { 3, 2 }, { 2 }, 1.0f, 1 },
  { { 4, 2 }, { 3 }, 1.0f, 1 },
  { { 5, 2 }, { 5 }, 1.0f, 1 },
  { { 1, 3 }, { 1 }, 1.0f, 1 },
  { { 2, 3 }, { 2 }, 1.0f, 1 },
  { { 3, 3 }, { 3 }, 1.0f, 1 },
  { { 4, 3 }, { 4 }, 1.0f, 1 },
  { { 5, 3 }, { 5 }, 1.0f, 1 },
  { { 1, 4 }, { 1 }, 1.0f, 1 },
  { { 2, 4 }, { 3 }, 1.0f, 1 },
  { { 3, 4 }, { 4 }, 1.0f, 1 },
  { { 4, 4 }, { 5 }, 1.0f, 1 },
  { { 5, 4 }, { 5 }, 1.0f, 1 },
  { { 1, 5 }, { 3 }, 1.0f, 1 },
  { { 2, 5 }, { 4 }, 1.0f, 1 },
  { { 3, 5 }, { 5 }, 1.0f, 1 },
  { { 4, 5 }, { 5 }, 1.0f, 1 },
  { { 5, 5 }, { 5 }, 1.0f, 1 }
};

void fuzzy_type11_eval_core(const float * in, float * out) {
    /* Input memberships. */
    float mu_in[FUZZY_NI][FUZZY_MAXMI];
    for (int i = 0; i < FUZZY_NI; i++)
        for (int m = 0; m < in_nmf[i]; m++)
            mu_in[i][m] = mf_eval(in_mf[i][m].type, in_mf[i][m].p, in[i]);

    /* Firing strength per rule (combine inputs by AND=t_norm / OR=s_norm). */
    float firing[FUZZY_NR];
    for (int r = 0; r < FUZZY_NR; r++) {
        float f = 1.0f;
        int seen = 0;
        for (int ii = 0; ii < FUZZY_NI; ii++) {
            int idx = rules[r].in[ii];
            if (idx != 0) {
                float v = mu_in[ii][idx - 1];
                f = seen ? ((rules[r].conn == 2) ? s_norm(f, v) : t_norm(f, v)) : v;
                seen = 1;
            }
        }
        firing[r] = (seen ? f : 1.0f) * rules[r].weight;
    }

    /* Precompute each output MF over the discretized universe. */
    float mu_out[FUZZY_NO][FUZZY_MAXMO][FUZZY_N];
    for (int o = 0; o < FUZZY_NO; o++)
        for (int m = 0; m < out_nmf[o]; m++)
            for (int k = 0; k < FUZZY_N; k++) {
                float y = out_lo[o] + (out_hi[o] - out_lo[o]) * (FUZZY_N == 1 ? 0.0f : (float) k / (float) (FUZZY_N - 1));
                mu_out[o][m][k] = mf_eval(out_mf[o][m].type, out_mf[o][m].p, y);
            }

    /* Aggregate + defuzzify each output. */
    for (int o = 0; o < FUZZY_NO; o++) {
        float agg[FUZZY_N];
        for (int k = 0; k < FUZZY_N; k++) {
            float a = 0.0f;
            for (int r = 0; r < FUZZY_NR; r++) {
                int oi = rules[r].out[o];
                if (oi == 0) continue;
                a = s_norm(a, imp(firing[r], mu_out[o][oi - 1][k]));
            }
            agg[k] = a;
        }
            {
                float num = 0.0f, den = 0.0f;
                for (int k = 0; k < FUZZY_N; k++) {
                    float y = out_lo[o] + (out_hi[o] - out_lo[o]) * (FUZZY_N == 1 ? 0.0f : (float) k / (float) (FUZZY_N - 1));
                    num += y * agg[k];
                    den += agg[k];
                }
                out[o] = (den > 1e-9f) ? num / den : 0.0f;
            }
    }
}


float fuzzy_type11_eval(float e, float ed) {
    float in[FUZZY_NI] = {e, ed};
    float out[FUZZY_NO];
    fuzzy_type11_eval_core(in, out);
    return out[0];
}
